[package]
name = "lemon_vm_bytecode_builder"
version = "0.1.0"
authors = ["enter"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lemonvm = { path = "../lemonvm2/" }
